require('core.plugin_config.lualine')
require('core.plugin_config.nvim-tree')
require('core.plugin_config.lsp_config')
require('core.plugin_config.treesitter')
require('core.plugin_config.completition')
require('core.plugin_config.theme')
